#!/bin/sh
echo "2-3" | sudo tee /sys/bus/usb/drivers/usb/unbind
echo "enabled" | sudo tee /sys/class/net/wlp3s0/device/power/wakeup
echo "enabled" | sudo tee /sys/class/net/enp0s31f6/device/power/wakeup
echo "enabled" | sudo tee /sys/bus/usb/devices/usb1/power/wakeup
echo "enabled" | sudo tee /sys/bus/usb/devices/usb2/power/wakeup
echo "enabled" | sudo tee /sys/bus/usb/devices/usb3/power/wakeup
echo "enabled" | sudo tee /sys/bus/usb/devices/usb4/power/wakeup
sudo powertop --auto-tune
# wttr-update
